using System.Collections.Generic;

namespace TradeXD
{
    public static class Constants
    {
        public enum ItemType
        {
            Unknown,
            BodyArmour,
            Boots,
            Gloves,
            Helmet,
            Amulet,
            Belt,
            Ring,
            OneHandWeapon,
            TwoHandWeapon
        }

        public static readonly Dictionary<string, ItemType> BaseItemType = new Dictionary<string, ItemType>
        {
            /* Body Armour */
            {"Plate Vest", ItemType.BodyArmour},
            {"Shabby Jerkin", ItemType.BodyArmour},
            {"Simple Robe", ItemType.BodyArmour},
            {"Chainmail Vest", ItemType.BodyArmour},
            {"Scale Vest", ItemType.BodyArmour},
            {"Padded Vest", ItemType.BodyArmour},
            {"Chestplate", ItemType.BodyArmour},
            {"Light Brigandine", ItemType.BodyArmour},
            {"Chainmail Tunic", ItemType.BodyArmour},
            {"Oiled Vest", ItemType.BodyArmour},
            {"Strapped Leather", ItemType.BodyArmour},
            {"Silken Vest", ItemType.BodyArmour},
            {"Scale Doublet", ItemType.BodyArmour},
            {"Ringmail Coat", ItemType.BodyArmour},
            {"Copper Plate", ItemType.BodyArmour},
            {"Buckskin Tunic", ItemType.BodyArmour},
            {"Padded Jacket", ItemType.BodyArmour},
            {"Scholar's Robe", ItemType.BodyArmour},
            {"Infantry Brigandine", ItemType.BodyArmour},
            {"Chainmail Doublet", ItemType.BodyArmour},
            {"War Plate", ItemType.BodyArmour},
            {"Oiled Coat", ItemType.BodyArmour},
            {"Wild Leather", ItemType.BodyArmour},
            {"Silken Garb", ItemType.BodyArmour},
            {"Full Plate", ItemType.BodyArmour},
            {"Mage's Vestment", ItemType.BodyArmour},
            {"Scarlet Raiment", ItemType.BodyArmour},
            {"Full Ringmail", ItemType.BodyArmour},
            {"Full Scale Armour", ItemType.BodyArmour},
            {"Full Leather", ItemType.BodyArmour},
            {"Soldier's Brigandine", ItemType.BodyArmour},
            {"Silk Robe", ItemType.BodyArmour},
            {"Waxed Garb", ItemType.BodyArmour},
            {"Arena Plate", ItemType.BodyArmour},
            {"Sun Leather", ItemType.BodyArmour},
            {"Full Chainmail", ItemType.BodyArmour},
            {"Holy Chainmail", ItemType.BodyArmour},
            {"Lordly Plate", ItemType.BodyArmour},
            {"Thief's Garb", ItemType.BodyArmour},
            {"Cabalist Regalia", ItemType.BodyArmour},
            {"Field Lamellar", ItemType.BodyArmour},
            {"Bone Armour", ItemType.BodyArmour},
            {"Eelskin Tunic", ItemType.BodyArmour},
            {"Bronze Plate", ItemType.BodyArmour},
            {"Sage's Robe", ItemType.BodyArmour},
            {"Wyrmscale Doublet", ItemType.BodyArmour},
            {"Latticed Ringmail", ItemType.BodyArmour},
            {"Quilted Jacket", ItemType.BodyArmour},
            {"Silken Wrap", ItemType.BodyArmour},
            {"Battle Plate", ItemType.BodyArmour},
            {"Frontier Leather", ItemType.BodyArmour},
            {"Hussar Brigandine", ItemType.BodyArmour},
            {"Crusader Chainmail", ItemType.BodyArmour},
            {"Sleek Coat", ItemType.BodyArmour},
            {"Sun Plate", ItemType.BodyArmour},
            {"Conjurer's Vestment", ItemType.BodyArmour},
            {"Glorious Leather", ItemType.BodyArmour},
            {"Full Wyrmscale", ItemType.BodyArmour},
            {"Ornate Ringmail", ItemType.BodyArmour},
            {"Crimson Raiment", ItemType.BodyArmour},
            {"Colosseum Plate", ItemType.BodyArmour},
            {"Coronal Leather", ItemType.BodyArmour},
            {"Spidersilk Robe", ItemType.BodyArmour},
            {"Commander's Brigandine", ItemType.BodyArmour},
            {"Chain Hauberk", ItemType.BodyArmour},
            {"Lacquered Garb", ItemType.BodyArmour},
            {"Majestic Plate", ItemType.BodyArmour},
            {"Cutthroat's Garb", ItemType.BodyArmour},
            {"Destroyer Regalia", ItemType.BodyArmour},
            {"Battle Lamellar", ItemType.BodyArmour},
            {"Devout Chainmail", ItemType.BodyArmour},
            {"Crypt Armour", ItemType.BodyArmour},
            {"Savant's Robe", ItemType.BodyArmour},
            {"Sharkskin Tunic", ItemType.BodyArmour},
            {"Golden Plate", ItemType.BodyArmour},
            {"Dragonscale Doublet", ItemType.BodyArmour},
            {"Loricated Ringmail", ItemType.BodyArmour},
            {"Sentinel Jacket", ItemType.BodyArmour},
            {"Necromancer Silks", ItemType.BodyArmour},
            {"Crusader Plate", ItemType.BodyArmour},
            {"Destiny Leather", ItemType.BodyArmour},
            {"Desert Brigandine", ItemType.BodyArmour},
            {"Conquest Chainmail", ItemType.BodyArmour},
            {"Occultist's Vestment", ItemType.BodyArmour},
            {"Exquisite Leather", ItemType.BodyArmour},
            {"Astral Plate", ItemType.BodyArmour},
            {"Varnished Coat", ItemType.BodyArmour},
            {"Full Dragonscale", ItemType.BodyArmour},
            {"Elegant Ringmail", ItemType.BodyArmour},
            {"Zodiac Leather", ItemType.BodyArmour},
            {"Gladiator Plate", ItemType.BodyArmour},
            {"Widowsilk Robe", ItemType.BodyArmour},
            {"Blood Raiment", ItemType.BodyArmour},
            {"General's Brigandine", ItemType.BodyArmour},
            {"Saint's Hauberk", ItemType.BodyArmour},
            {"Glorious Plate", ItemType.BodyArmour},
            {"Assassin's Garb", ItemType.BodyArmour},
            {"Vaal Regalia", ItemType.BodyArmour},
            {"Sadist Garb", ItemType.BodyArmour},
            {"Triumphant Lamellar", ItemType.BodyArmour},
            {"Saintly Chainmail", ItemType.BodyArmour},
            {"Carnal Armour", ItemType.BodyArmour},
            {"Sacrificial Garb", ItemType.BodyArmour},

            /* Boots */
            {"Iron Greaves", ItemType.Boots},
            {"Rawhide Boots", ItemType.Boots},
            {"Wool Shoes", ItemType.Boots},
            {"Chain Boots", ItemType.Boots},
            {"Wrapped Boots", ItemType.Boots},
            {"Leatherscale Boots", ItemType.Boots},
            {"Velvet Slippers", ItemType.Boots},
            {"Steel Greaves", ItemType.Boots},
            {"Goathide Boots", ItemType.Boots},
            {"Ringmail Boots", ItemType.Boots},
            {"Strapped Boots", ItemType.Boots},
            {"Ironscale Boots", ItemType.Boots},
            {"Deerskin Boots", ItemType.Boots},
            {"Silk Slippers", ItemType.Boots},
            {"Plated Greaves", ItemType.Boots},
            {"Clasped Boots", ItemType.Boots},
            {"Mesh Boots", ItemType.Boots},
            {"Bronzescale Boots", ItemType.Boots},
            {"Scholar Boots", ItemType.Boots},
            {"Reinforced Greaves", ItemType.Boots},
            {"Nubuck Boots", ItemType.Boots},
            {"Shackled Boots", ItemType.Boots},
            {"Steelscale Boots", ItemType.Boots},
            {"Riveted Boots", ItemType.Boots},
            {"Antique Greaves", ItemType.Boots},
            {"Satin Slippers", ItemType.Boots},
            {"Eelskin Boots", ItemType.Boots},
            {"Zealot Boots", ItemType.Boots},
            {"Trapper Boots", ItemType.Boots},
            {"Serpentscale Boots", ItemType.Boots},
            {"Samite Slippers", ItemType.Boots},
            {"Sharkskin Boots", ItemType.Boots},
            {"Ancient Greaves", ItemType.Boots},
            {"Ambush Boots", ItemType.Boots},
            {"Soldier Boots", ItemType.Boots},
            {"Wyrmscale Boots", ItemType.Boots},
            {"Conjurer Boots", ItemType.Boots},
            {"Goliath Greaves", ItemType.Boots},
            {"Carnal Boots", ItemType.Boots},
            {"Shagreen Boots", ItemType.Boots},
            {"Legion Boots", ItemType.Boots},
            {"Hydrascale Boots", ItemType.Boots},
            {"Arcanist Slippers", ItemType.Boots},
            {"Vaal Greaves", ItemType.Boots},
            {"Stealth Boots", ItemType.Boots},
            {"Assassin's Boots", ItemType.Boots},
            {"Crusader Boots", ItemType.Boots},
            {"Dragonscale Boots", ItemType.Boots},
            {"Sorcerer Boots", ItemType.Boots},
            {"Titan Greaves", ItemType.Boots},
            {"Slink Boots", ItemType.Boots},
            {"Murder Boots", ItemType.Boots},
            {"Two-Toned Boots", ItemType.Boots},

            /* Gloves */
            {"Iron Gauntlets", ItemType.Gloves},
            {"Rawhide Gloves", ItemType.Gloves},
            {"Wool Gloves", ItemType.Gloves},
            {"Fishscale Gauntlets", ItemType.Gloves},
            {"Wrapped Mitts", ItemType.Gloves},
            {"Chain Gloves", ItemType.Gloves},
            {"Goathide Gloves", ItemType.Gloves},
            {"Plated Gauntlets", ItemType.Gloves},
            {"Velvet Gloves", ItemType.Gloves},
            {"Ironscale Gauntlets", ItemType.Gloves},
            {"Strapped Mitts", ItemType.Gloves},
            {"Ringmail Gloves", ItemType.Gloves},
            {"Deerskin Gloves", ItemType.Gloves},
            {"Bronze Gauntlets", ItemType.Gloves},
            {"Silk Gloves", ItemType.Gloves},
            {"Bronzescale Gauntlets", ItemType.Gloves},
            {"Clasped Mitts", ItemType.Gloves},
            {"Mesh Gloves", ItemType.Gloves},
            {"Nubuck Gloves", ItemType.Gloves},
            {"Steel Gauntlets", ItemType.Gloves},
            {"Embroidered Gloves", ItemType.Gloves},
            {"Trapper Mitts", ItemType.Gloves},
            {"Steelscale Gauntlets", ItemType.Gloves},
            {"Riveted Gloves", ItemType.Gloves},
            {"Eelskin Gloves", ItemType.Gloves},
            {"Antique Gauntlets", ItemType.Gloves},
            {"Satin Gloves", ItemType.Gloves},
            {"Zealot Gloves", ItemType.Gloves},
            {"Serpentscale Gauntlets", ItemType.Gloves},
            {"Ambush Mitts", ItemType.Gloves},
            {"Sharkskin Gloves", ItemType.Gloves},
            {"Samite Gloves", ItemType.Gloves},
            {"Ancient Gauntlets", ItemType.Gloves},
            {"Wyrmscale Gauntlets", ItemType.Gloves},
            {"Carnal Mitts", ItemType.Gloves},
            {"Soldier Gloves", ItemType.Gloves},
            {"Goliath Gauntlets", ItemType.Gloves},
            {"Shagreen Gloves", ItemType.Gloves},
            {"Conjurer Gloves", ItemType.Gloves},
            {"Legion Gloves", ItemType.Gloves},
            {"Assassin's Mitts", ItemType.Gloves},
            {"Hydrascale Gauntlets", ItemType.Gloves},
            {"Arcanist Gloves", ItemType.Gloves},
            {"Stealth Gloves", ItemType.Gloves},
            {"Vaal Gauntlets", ItemType.Gloves},
            {"Crusader Gloves", ItemType.Gloves},
            {"Murder Mitts", ItemType.Gloves},
            {"Dragonscale Gauntlets", ItemType.Gloves},
            {"Titan Gauntlets", ItemType.Gloves},
            {"Sorcerer Gloves", ItemType.Gloves},
            {"Slink Gloves", ItemType.Gloves},
            {"Gripped Gloves", ItemType.Gloves},
            {"Fingerless Silk Gloves", ItemType.Gloves},
            {"Spiked Gloves", ItemType.Gloves},

            /* Helmets */
            {"Iron Hat", ItemType.Helmet},
            {"Vine Circlet", ItemType.Helmet},
            {"Leather Cap", ItemType.Helmet},
            {"Scare Mask", ItemType.Helmet},
            {"Battered Helm", ItemType.Helmet},
            {"Rusted Coif", ItemType.Helmet},
            {"Cone Helmet", ItemType.Helmet},
            {"Iron Circlet", ItemType.Helmet},
            {"Tricorne", ItemType.Helmet},
            {"Plague Mask", ItemType.Helmet},
            {"Soldier Helmet", ItemType.Helmet},
            {"Sallet", ItemType.Helmet},
            {"Iron Mask", ItemType.Helmet},
            {"Torture Cage", ItemType.Helmet},
            {"Barbute Helmet", ItemType.Helmet},
            {"Leather Hood", ItemType.Helmet},
            {"Great Helmet", ItemType.Helmet},
            {"Visored Sallet", ItemType.Helmet},
            {"Close Helmet", ItemType.Helmet},
            {"Tribal Circlet", ItemType.Helmet},
            {"Festival Mask", ItemType.Helmet},
            {"Wolf Pelt", ItemType.Helmet},
            {"Crusader Helmet", ItemType.Helmet},
            {"Gilded Sallet", ItemType.Helmet},
            {"Bone Circlet", ItemType.Helmet},
            {"Gladiator Helmet", ItemType.Helmet},
            {"Golden Mask", ItemType.Helmet},
            {"Secutor Helm", ItemType.Helmet},
            {"Aventail Helmet", ItemType.Helmet},
            {"Raven Mask", ItemType.Helmet},
            {"Lunaris Circlet", ItemType.Helmet},
            {"Reaver Helmet", ItemType.Helmet},
            {"Hunter Hood", ItemType.Helmet},
            {"Fencer Helm", ItemType.Helmet},
            {"Zealot Helmet", ItemType.Helmet},
            {"Callous Mask", ItemType.Helmet},
            {"Noble Tricorne", ItemType.Helmet},
            {"Steel Circlet", ItemType.Helmet},
            {"Siege Helmet", ItemType.Helmet},
            {"Lacquered Helmet", ItemType.Helmet},
            {"Regicide Mask", ItemType.Helmet},
            {"Great Crown", ItemType.Helmet},
            {"Necromancer Circlet", ItemType.Helmet},
            {"Ursine Pelt", ItemType.Helmet},
            {"Samite Helmet", ItemType.Helmet},
            {"Harlequin Mask", ItemType.Helmet},
            {"Magistrate Crown", ItemType.Helmet},
            {"Fluted Bascinet", ItemType.Helmet},
            {"Solaris Circlet", ItemType.Helmet},
            {"Silken Hood", ItemType.Helmet},
            {"Ezomyte Burgonet", ItemType.Helmet},
            {"Vaal Mask", ItemType.Helmet},
            {"Pig-Faced Bascinet", ItemType.Helmet},
            {"Prophet Crown", ItemType.Helmet},
            {"Sinner Tricorne", ItemType.Helmet},
            {"Mind Cage", ItemType.Helmet},
            {"Royal Burgonet", ItemType.Helmet},
            {"Deicide Mask", ItemType.Helmet},
            {"Nightmare Bascinet", ItemType.Helmet},
            {"Praetor Crown", ItemType.Helmet},
            {"Hubris Circlet", ItemType.Helmet},
            {"Eternal Burgonet", ItemType.Helmet},
            {"Lion Pelt", ItemType.Helmet},
            {"Bone Helmet", ItemType.Helmet},

            /* Amulet */
            {"Spinefuse Talisman", ItemType.Amulet},
            {"Mandible Talisman", ItemType.Amulet},
            {"Hexclaw Talisman", ItemType.Amulet},
            {"Primal Skull Talisman", ItemType.Amulet},
            {"Wereclaw Talisman", ItemType.Amulet},
            {"Splitnewt Talisman", ItemType.Amulet},
            {"Clutching Talisman", ItemType.Amulet},
            {"Avian Twins Talisman", ItemType.Amulet},
            {"Fangjaw Talisman", ItemType.Amulet},
            {"Horned Talisman", ItemType.Amulet},
            {"Three Rat Talisman", ItemType.Amulet},
            {"Monkey Twins Talisman", ItemType.Amulet},
            {"Longtooth Talisman", ItemType.Amulet},
            {"Rotfeather Talisman", ItemType.Amulet},
            {"Monkey Paw Talisman", ItemType.Amulet},
            {"Three Hands Talisman", ItemType.Amulet},
            {"Jet Amulet", ItemType.Amulet},
            {"Black Maw Talisman", ItemType.Amulet},
            {"Bonespire Talisman", ItemType.Amulet},
            {"Ashscale Talisman", ItemType.Amulet},
            {"Lone Antler Talisman", ItemType.Amulet},
            {"Deep One Talisman", ItemType.Amulet},
            {"Breakrib Talisman", ItemType.Amulet},
            {"Deadhand Talisman", ItemType.Amulet},
            {"Undying Flesh Talisman", ItemType.Amulet},
            {"Rot Head Talisman", ItemType.Amulet},
            {"Paua Amulet", ItemType.Amulet},
            {"Coral Amulet", ItemType.Amulet},
            {"Lapis Amulet", ItemType.Amulet},
            {"Jade Amulet", ItemType.Amulet},
            {"Amber Amulet", ItemType.Amulet},
            {"Gold Amulet", ItemType.Amulet},
            {"Turquoise Amulet", ItemType.Amulet},
            {"Agate Amulet", ItemType.Amulet},
            {"Citrine Amulet", ItemType.Amulet},
            {"Onyx Amulet", ItemType.Amulet},
            {"Writhing Talisman", ItemType.Amulet},
            {"Chrysalis Talisman", ItemType.Amulet},
            {"Ruby Amulet", ItemType.Amulet},
            {"Marble Amulet", ItemType.Amulet},
            {"Blue Pearl Amulet", ItemType.Amulet},

            /* Belts */
            {"Rustic Sash", ItemType.Belt},
            {"Chain Belt", ItemType.Belt},
            {"Leather Belt", ItemType.Belt},
            {"Heavy Belt", ItemType.Belt},
            {"Golden Obi", ItemType.Belt},
            {"Studded Belt", ItemType.Belt},
            {"Cloth Belt", ItemType.Belt},
            {"Vanguard Belt", ItemType.Belt},
            {"Crystal Belt", ItemType.Belt},

            /* Rings */
            {"Breach Ring", ItemType.Ring},
            {"Iron Ring", ItemType.Ring},
            {"Coral Ring", ItemType.Ring},
            {"Paua Ring", ItemType.Ring},
            {"Sapphire Ring", ItemType.Ring},
            {"Topaz Ring", ItemType.Ring},
            {"Golden Hoop", ItemType.Ring},
            {"Jet Ring", ItemType.Ring},
            {"Ruby Ring", ItemType.Ring},
            {"Gold Ring", ItemType.Ring},
            {"Two-Stone Ring", ItemType.Ring},
            {"Diamond Ring", ItemType.Ring},
            {"Moonstone Ring", ItemType.Ring},
            {"Prismatic Ring", ItemType.Ring},
            {"Amethyst Ring", ItemType.Ring},
            {"Unset Ring", ItemType.Ring},
            {"Steel Ring", ItemType.Ring},
            {"Opal Ring", ItemType.Ring},

            /* 1x3 Weapons */
            {"Glass Shank", ItemType.OneHandWeapon},
            {"Skinning Knife", ItemType.OneHandWeapon},
            {"Carving Knife", ItemType.OneHandWeapon},
            {"Stiletto", ItemType.OneHandWeapon},
            {"Boot Knife", ItemType.OneHandWeapon},
            {"Copper Kris", ItemType.OneHandWeapon},
            {"Skean", ItemType.OneHandWeapon},
            {"Imp Dagger", ItemType.OneHandWeapon},
            {"Flaying Knife", ItemType.OneHandWeapon},
            {"Prong Dagger", ItemType.OneHandWeapon},
            {"Butcher Knife", ItemType.OneHandWeapon},
            {"Poignard", ItemType.OneHandWeapon},
            {"Boot Blade", ItemType.OneHandWeapon},
            {"Golden Kris", ItemType.OneHandWeapon},
            {"Royal Skean", ItemType.OneHandWeapon},
            {"Fiend Dagger", ItemType.OneHandWeapon},
            {"Trisula", ItemType.OneHandWeapon},
            {"Gutting Knife", ItemType.OneHandWeapon},
            {"Slaughter Knife", ItemType.OneHandWeapon},
            {"Ambusher", ItemType.OneHandWeapon},
            {"Ezomyte Dagger", ItemType.OneHandWeapon},
            {"Platinum Kris", ItemType.OneHandWeapon},
            {"Imperial Skean", ItemType.OneHandWeapon},
            {"Demon Dagger", ItemType.OneHandWeapon},
            {"Sai", ItemType.OneHandWeapon},
            {"Rusted Sword", ItemType.OneHandWeapon},
            {"Copper Sword", ItemType.OneHandWeapon},
            {"Sabre", ItemType.OneHandWeapon},
            {"Cutlass", ItemType.OneHandWeapon},
            {"Gemstone Sword", ItemType.OneHandWeapon},
            {"Corsair Sword", ItemType.OneHandWeapon},
            {"Driftwood Wand", ItemType.OneHandWeapon},
            {"Goat's Horn", ItemType.OneHandWeapon},
            {"Carved Wand", ItemType.OneHandWeapon},
            {"Quartz Wand", ItemType.OneHandWeapon},
            {"Spiraled Wand", ItemType.OneHandWeapon},
            {"Sage Wand", ItemType.OneHandWeapon},
            {"Pagan Wand", ItemType.OneHandWeapon},
            {"Faun's Horn", ItemType.OneHandWeapon},
            {"Engraved Wand", ItemType.OneHandWeapon},
            {"Crystal Wand", ItemType.OneHandWeapon},
            {"Serpent Wand", ItemType.OneHandWeapon},
            {"Omen Wand", ItemType.OneHandWeapon},
            {"Heathen Wand", ItemType.OneHandWeapon},
            {"Demon's Horn", ItemType.OneHandWeapon},
            {"Imbued Wand", ItemType.OneHandWeapon},
            {"Opal Wand", ItemType.OneHandWeapon},
            {"Tornado Wand", ItemType.OneHandWeapon},
            {"Prophecy Wand", ItemType.OneHandWeapon},
            {"Profane Wand", ItemType.OneHandWeapon},

            /* 2x3 Weapons */
            {"Crude Bow", ItemType.TwoHandWeapon},
            {"Short Bow", ItemType.TwoHandWeapon},
            {"Grove Bow", ItemType.TwoHandWeapon},
            {"Thicket Bow", ItemType.TwoHandWeapon}
        };
    }
}